apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'while true; do sleep 3600; done']
      livenessProbe:
        exec:
          command: ["echo", "Hello, World!"]
        # initial delay of 5 sec before it start checking
        initialDelaySeconds: 5
        # it will run every 5 sec
        periodSeconds: 5

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ready-if-service-ready
  name: ready-if-service-ready
spec:
  containers:
    - image: nginx:1.16.1-alpine
      name: ready-if-service-ready
      resources: {}
      livenessProbe:
        exec:
          command:
            - 'true'
      readinessProbe:
        exec:
          command:
            - sh
            - -c
            - 'wget -T2 -O- http://service-am-i-ready:80'
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}