apiVersion: v1
kind: Pod
metadata:
  name: startup-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.19.1
      startupProbe:
        httpGet:
          path: /
          port: 80
        # wait little bit longer for application to start before it fails
        failureThreshold: 30
        # it will run every 5 sec
        periodSeconds: 10