apiVersion: v1
data:
  halt: IyEgL2Jpbi9zaAo...
kind: Secret
metadata:
  creationTimestamp: null
  name: secret1
  namespace: secret
---
or

k -n secret create secret generic secret2 --from-literal=user=user1 --from-literal=pass=1234

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-pod
  name: secret-pod
  namespace: secret
spec:
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
  containers:
    - args:
        - sh
        - -c
        - sleep 1d
      image: busybox:1.31.1
      name: secret-pod
      resources: {}
      env:
        - name: APP_USER
          valueFrom:
            secretKeyRef:
              name: secret2
              key: user
        - name: APP_PASS
          valueFrom:
            secretKeyRef:
              name: secret2
              key: pass
      volumeMounts:
        - name: secret1
          mountPath: /tmp/secret1
          readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: secret1
      secret:
        secretName: secret1

---

- name: SPECIAL_LEVEL_KEY
  valueFrom:
    configMapKeyRef:
      name: special-config
      key: special.how