apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod-http
spec:
  containers:
    - name: nginx
      image: nginx:1.19.1
      livenessProbe:
        httpGet:
          path: /
          port: 80
        # initial delay of 5 sec before it start checking
        initialDelaySeconds: 5
        # it will run every 5 sec
        periodSeconds: 5