apiVersion: v1
kind: Pod
metadata:
  name: never-pod
spec:
  # pod will restart when the container is failed to start, will not restart if succeed, it wil stay in completed.
  restartPolicy: Never
  containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c' 'sleep 10; this is bad cmd that will fail']
