apiVersion: v1
kind: Pod
metadata:
  name: onfailure-pod
spec:
  # pod will never restart, if there is error it will stay in error state.
  restartPolicy: Never
  containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c' 'sleep 10; this is bad cmd that will fail']
