apiVersion: v1
kind: PersistentVolume
metadata:
  name: localstorage
spec:
  storageClassName: <storageClassName>
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: <localPath>
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - <hostName>